[project]
name = "comfyui-huggingface-nodes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "diffusers[torch]>=0.20.0",
    "huggingface-hub>=0.20.0",
]
